[package]
name = "test_intellij"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
lazy_static = "1.4.0"
chrono = "0.4.19"
lettre = "0.9.6"
lettre_email = "0.9"
native-tls = "0.2.8"